import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from "@/components/estructura/header";
import Main from "@/components/estructura/main";
import Footer from "@/components/estructura/footer";
import Nav from "@/components/estructura/nav";
import CarouselList from '@/components/reutilizables/carouselList';
import Memoria from '@/servicios/memoria';
import ResponsiveNav from '@/components/estructura/responsiveNav';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children:React.ReactNode
}) 
{
  return (
    <html lang="en">
      <body >
        <Nav></Nav>
        <Memoria>
        <Header></Header>
        <Main>
          <CarouselList></CarouselList>
        </Main>
        {props.children}
        </Memoria>
        <Footer></Footer>
        <ResponsiveNav></ResponsiveNav>
      </body>
    </html>
  )
}
