import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from "../components/estructura/header";
import Main from "../components/estructura/main";
import Footer from "../components/estructura/footer";
import Nav from "../components/estructura/nav";
import Carousel from '@/components/reutilizables/carousel';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children:React.ReactNode
}) 
{

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav></Nav>
        <Header></Header>
        <Main>
          <Carousel id='carusel1' title='carusel1'></Carousel>
          {props.children}
        </Main>
        <Footer></Footer>
      </body>
    </html>
  )
}
